root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
args = ["-buildvcs=false"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "client/node_modules", "client/build"]
exclude_regex = ["_test.go"]
delay = 1000

[log]
time = true
